### ISSUE TITLE
Could we have an end-to-end example for IF?

### ISSUE THREAD

**Issue by tildebyte** [Zuellni/ComfyUI-Custom-Nodes#2]
I've tried everything I can think of on a RunPod with an RTX A6000 w/48G VRAM, and I simply get errors every time.

I'd open issues for the errors, but the variety of errors I see and the circumstances which cause them is a matrix I don't feel like filling out today...

### If I had an example Comfy network which I *knew* was properly configured, it's be a lot easier for me to troubleshoot.

Notes:

- I've used the same pod type/similar image to run inference with IF from a VSCode notebook (straight code, using DF's 'dream' script - not even using diffusers) so it doesn't seem likely to be the pod or the container...
- This specific pod/container combo is great for straight SD, including custom checkpoints/LORAs/C-Nets, etc.
- I *did* manage to get the Stage III node to do an upscale without puking

A couple of examples:

- ` AttributeError: 'NoneType' object has no attribute 'forward'` (I *think* this was default "device", or with "device" specified as 'cpu')
- `RuntimeError: Expected weight to be a vector of size equal to the number of channels in input, but got weight of shape [2816] and input of shape [2, 4096, 77]` (pretty sure this was with "device" set to 'cuda', but other factors were almost certainly in play)

FWIW, the container is https://hub.docker.com/r/quaestor/focal-py310-torch2_1_nightly-cu118-comfy-extras [1], based on https://github.com/runpod/containers/blob/main/torch/Dockerfile (i.e. https://hub.docker.com/r/runpod/pytorch), which contains Python 3.10, PyTorch 2.1 nightly, CUDA 11.8, ComfyUI (+models), with tons of Comfy extras. It does NOT yet contain the DF IF models (which is what I'm currently working on)

[1] It *should* be publicly visible

**Comment by Zuellni** [comment]
![image_workflow](https://github.com/Zuellni/ComfyUI-Custom-Nodes/assets/123005779/6f638a02-f475-4b81-bcf6-2981b236b957)
Here's an IF workflow (you can load the image in Comfy). Afraid I can't really do much else with this info, please post the full console log and a workflow that's causing you problems. You shouldn't have to specify any devices with 48GB of VRAM. Also torch nightly probably isn't the best choice for testing nodes, not even sure bitsandbytes works with it.

**Comment by tildebyte** [comment]
There was nothing important before what's here; just the model starting to download

```2023-05-29T14:39:12.902004501Z 
Downloading (…)of-00002.safetensors:  60%|██████    | 6.00G/9.96G [01:01<00:34, 116MB/s]
2023-05-29T14:39:13.080634687Z 
Downloading (…)of-00002.safetensors:  60%|██████    | 6.02G/9.96G [01:01<00:33, 116MB/s]
** snip **
2023-05-29T14:39:52.039529084Z 
Downloading (…)of-00002.safetensors: 100%|█████████▉| 9.95G/9.96G [01:40<00:00, 115MB/s]
Downloading (…)of-00002.safetensors: 100%|██████████| 9.96G/9.96G [01:40<00:00, 98.6MB/s]
2023-05-29T14:39:52.203176557Z 
Downloading shards:  50%|█████     | 1/2 [01:41<01:41, 101.21s/it]
2023-05-29T14:39:52.404517307Z 
Downloading (…)of-00002.safetensors:   0%|          | 0.00/1.58G [00:00<?, ?B/s]
2023-05-29T14:39:52.522835164Z 
Downloading (…)of-00002.safetensors:   1%|          | 10.5M/1.58G [00:00<00:30, 52.1MB/s]
2023-05-29T14:39:52.702919920Z 
Downloading (…)of-00002.safetensors:   1%|▏         | 21.0M/1.58G [00:00<00:22, 68.8MB/s]
** snip **
2023-05-29T14:40:06.914485486Z 
Downloading (…)of-00002.safetensors: 100%|██████████| 1.58G/1.58G [00:14<00:00, 89.4MB/s]
Downloading (…)of-00002.safetensors: 100%|██████████| 1.58G/1.58G [00:14<00:00, 107MB/s] 
2023-05-29T14:40:06.915516526Z 
Downloading shards: 100%|██████████| 2/2 [01:56<00:00, 50.42s/it] 
Downloading shards: 100%|██████████| 2/2 [01:56<00:00, 58.04s/it]
2023-05-29T14:40:06.946628181Z /usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/nvidia/lib'), PosixPath('/usr/local/lib/python3.10/dist-packages/cv2/../../lib64'), PosixPath('/usr/local/nvidia/lib64')}
2023-05-29T14:40:06.946660541Z   warn(msg)
2023-05-29T14:40:06.946666431Z /usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /usr/local/lib/python3.10/dist-packages/cv2/../../lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/lib/x86_64-linux-gnu did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
2023-05-29T14:40:06.946671341Z   warn(msg)
2023-05-29T14:40:06.946674431Z /usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('noninteractive    SHELL=/bin/bash')}
2023-05-29T14:40:06.946678081Z   warn(msg)
2023-05-29T14:40:06.946680991Z /usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so'), PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0')}.. We'll flip a coin and try one of these, in order to fail forward.
2023-05-29T14:40:06.946684921Z Either way, this might cause trouble in the future:
2023-05-29T14:40:06.946688031Z If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
2023-05-29T14:40:06.946697241Z   warn(msg)
2023-05-29T14:40:07.699065980Z 
2023-05-29T14:40:07.699091370Z ===================================BUG REPORT===================================
2023-05-29T14:40:07.699097170Z Welcome to bitsandbytes. For bug reports, please run
2023-05-29T14:40:07.699100950Z 
2023-05-29T14:40:07.699103910Z python -m bitsandbytes
2023-05-29T14:40:07.699107020Z 
2023-05-29T14:40:07.699110470Z  and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
2023-05-29T14:40:07.699113910Z ================================================================================
2023-05-29T14:40:07.699116920Z bin /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda118.so
2023-05-29T14:40:07.699120110Z CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
2023-05-29T14:40:07.699123220Z CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
2023-05-29T14:40:07.699126280Z CUDA SETUP: Highest compute capability among GPUs detected: 8.6
2023-05-29T14:40:07.699129310Z CUDA SETUP: Detected CUDA version 118
2023-05-29T14:40:07.699132350Z CUDA SETUP: Loading binary /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda118.so...
2023-05-29T14:40:09.211685449Z 
Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]
Loading checkpoint shards:  50%|█████     | 1/2 [00:01<00:01,  1.24s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:01<00:00,  1.49it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:01<00:00,  1.32it/s]
2023-05-29T14:40:10.155819746Z 
  0%|          | 0/30 [00:00<?, ?it/s]
  0%|          | 0/30 [00:00<?, ?it/s]
2023-05-29T14:43:34.661211334Z Traceback (most recent call last):
2023-05-29T14:43:34.661257294Z   File "/ComfyUI/execution.py", line 257, in execute
2023-05-29T14:43:34.661264034Z     recursive_execute(self.server, prompt, self.outputs, x, extra_data, executed, prompt_id, self.outputs_ui)
2023-05-29T14:43:34.661267964Z   File "/ComfyUI/execution.py", line 120, in recursive_execute
2023-05-29T14:43:34.661271374Z     recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed, prompt_id, outputs_ui)
2023-05-29T14:43:34.661274654Z   File "/ComfyUI/execution.py", line 128, in recursive_execute
2023-05-29T14:43:34.661277844Z     output_data, output_ui = get_output_data(obj, input_data_all)
2023-05-29T14:43:34.661281254Z   File "/ComfyUI/execution.py", line 75, in get_output_data
2023-05-29T14:43:34.661284364Z     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
2023-05-29T14:43:34.661287554Z   File "/ComfyUI/execution.py", line 68, in map_node_over_list
2023-05-29T14:43:34.661290574Z     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
2023-05-29T14:43:34.661300834Z   File "/ComfyUI/custom_nodes/ComfyUI-Custom-Nodes/Nodes/IF.py", line 159, in process
2023-05-29T14:43:34.661304394Z     images = model(
2023-05-29T14:43:34.661307344Z   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2023-05-29T14:43:34.661310634Z     return func(*args, **kwargs)
2023-05-29T14:43:34.661313604Z   File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/deepfloyd_if/pipeline_if.py", line 792, in __call__
2023-05-29T14:43:34.661316854Z     noise_pred = self.unet(
2023-05-29T14:43:34.661319904Z   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
2023-05-29T14:43:34.661323304Z     return forward_call(*args, **kwargs)
2023-05-29T14:43:34.661326294Z   File "/usr/local/lib/python3.10/dist-packages/accelerate/hooks.py", line 165, in new_forward
2023-05-29T14:43:34.661329554Z     output = old_forward(*args, **kwargs)
2023-05-29T14:43:34.661332544Z   File "/usr/local/lib/python3.10/dist-packages/diffusers/models/unet_2d_condition.py", line 813, in forward
2023-05-29T14:43:34.661335744Z     sample, res_samples = downsample_block(
2023-05-29T14:43:34.661338674Z   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
2023-05-29T14:43:34.661341934Z     return forward_call(*args, **kwargs)
2023-05-29T14:43:34.661344914Z   File "/usr/local/lib/python3.10/dist-packages/diffusers/models/unet_2d_blocks.py", line 1582, in forward
2023-05-29T14:43:34.661348164Z     hidden_states = attn(
2023-05-29T14:43:34.661351234Z   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
2023-05-29T14:43:34.661354454Z     return forward_call(*args, **kwargs)
2023-05-29T14:43:34.661358624Z   File "/usr/local/lib/python3.10/dist-packages/diffusers/models/attention_processor.py", line 312, in forward
2023-05-29T14:43:34.661362044Z     return self.processor(
2023-05-29T14:43:34.661365044Z   File "/usr/local/lib/python3.10/dist-packages/diffusers/models/attention_processor.py", line 770, in __call__
2023-05-29T14:43:34.661368354Z     encoder_hidden_states = attn.norm_encoder_hidden_states(encoder_hidden_states)
2023-05-29T14:43:34.661371544Z   File "/usr/local/lib/python3.10/dist-packages/diffusers/models/attention_processor.py", line 425, in norm_encoder_hidden_states
2023-05-29T14:43:34.661375384Z     encoder_hidden_states = self.norm_cross(encoder_hidden_states)
2023-05-29T14:43:34.661378394Z   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
2023-05-29T14:43:34.661381664Z     return forward_call(*args, **kwargs)
2023-05-29T14:43:34.661384674Z   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/normalization.py", line 273, in forward
2023-05-29T14:43:34.661387934Z     return F.group_norm(
2023-05-29T14:43:34.661391054Z   File "/usr/local/lib/python3.10/dist-packages/torch/nn/functional.py", line 2550, in group_norm
2023-05-29T14:43:34.661397054Z     return torch.group_norm(input, num_groups, weight, bias, eps, torch.backends.cudnn.enabled)
2023-05-29T14:43:34.661400314Z RuntimeError: Expected weight to be a vector of size equal to the number of channels in input, but got weight of shape [768] and input of shape [2, 4096, 77]
2023-05-29T14:43:34.661403674Z 
2023-05-29T14:43:34.661406644Z Prompt executed in 140.53 seconds
2023-05-29T14:43:34.661409674Z got prompt
2023-05-29T14:43:34.671371535Z 
  0%|          | 0/30 [00:00<?, ?it/s]
  0%|          | 0/30 [00:00<?, ?it/s]
```

Weirdly, the traceback doesn't actually show up in the logs until I trigger the queue a *second* time... it simply stops running and doesn't show anything the first time.

Next step for me is to roll back to earlier torch...

Thanks for the quick help!

**Comment by tildebyte** [comment]
:( refreshed torch/torchaudio/torchvision to 2.0, diffusers/transformers to latest git, restarted, switched to T5-16, and now I'm seeing the *other* error

```
2023-05-29T15:16:30.888230068Z got prompt
2023-05-29T15:16:30.888677588Z 
Downloading shards:   0%|          | 0/2 [00:00<?, ?it/s]
Downloading shards: 100%|██████████| 2/2 [00:00<00:00, 5652.70it/s]
2023-05-29T15:17:05.884778232Z 
Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]
Loading checkpoint shards:  50%|█████     | 1/2 [00:01<00:01,  1.39s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:01<00:00,  1.37it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:01<00:00,  1.21it/s]
2023-05-29T15:17:32.756095267Z Traceback (most recent call last):
2023-05-29T15:17:32.756140447Z   File "/ComfyUI/execution.py", line 257, in execute
2023-05-29T15:17:32.756146887Z     recursive_execute(self.server, prompt, self.outputs, x, extra_data, executed, prompt_id, self.outputs_ui)
2023-05-29T15:17:32.756150937Z   File "/ComfyUI/execution.py", line 120, in recursive_execute
2023-05-29T15:17:32.756154637Z     recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed, prompt_id, outputs_ui)
2023-05-29T15:17:32.756158907Z   File "/ComfyUI/execution.py", line 120, in recursive_execute
2023-05-29T15:17:32.756162547Z     recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed, prompt_id, outputs_ui)
2023-05-29T15:17:32.756166157Z   File "/ComfyUI/execution.py", line 120, in recursive_execute
2023-05-29T15:17:32.756170067Z     recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed, prompt_id, outputs_ui)
2023-05-29T15:17:32.756173407Z   File "/ComfyUI/execution.py", line 128, in recursive_execute
2023-05-29T15:17:32.756176477Z     output_data, output_ui = get_output_data(obj, input_data_all)
2023-05-29T15:17:32.756179747Z   File "/ComfyUI/execution.py", line 75, in get_output_data
2023-05-29T15:17:32.756183157Z     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
2023-05-29T15:17:32.756187137Z   File "/ComfyUI/execution.py", line 68, in map_node_over_list
2023-05-29T15:17:32.756190387Z     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
2023-05-29T15:17:32.756193447Z   File "/ComfyUI/custom_nodes/ComfyUI-Custom-Nodes/Nodes/IF.py", line 100, in process
2023-05-29T15:17:32.756196627Z     model.enable_model_cpu_offload()
2023-05-29T15:17:32.756199737Z   File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/deepfloyd_if/pipeline_if.py", line 201, in enable_model_cpu_offload
2023-05-29T15:17:32.756203177Z     _, hook = cpu_offload_with_hook(self.unet, device, prev_module_hook=hook)
2023-05-29T15:17:32.756206267Z   File "/usr/local/lib/python3.10/dist-packages/accelerate/big_modeling.py", line 233, in cpu_offload_with_hook
2023-05-29T15:17:32.756209607Z     add_hook_to_module(model, hook, append=True)
2023-05-29T15:17:32.756212607Z   File "/usr/local/lib/python3.10/dist-packages/accelerate/hooks.py", line 152, in add_hook_to_module
2023-05-29T15:17:32.756215927Z     old_forward = module.forward
2023-05-29T15:17:32.756218907Z AttributeError: 'NoneType' object has no attribute 'forward'
2023-05-29T15:17:32.756221987Z 
2023-05-29T15:17:32.756224877Z Prompt executed in 38.60 seconds
2023-05-29T15:17:32.756237047Z got prompt
2023-05-29T15:17:32.756649247Z 
Downloading shards:   0%|          | 0/2 [00:00<?, ?it/s]
Downloading shards: 100%|██████████| 2/2 [00:00<00:00, 6269.51it/s]
```

**Comment by Zuellni** [comment]
The first error seems to be a problem with offloading the 16 bit text encoder to cpu, I was under the impression diffusers fixed this already since I stopped getting it but guess not. Setting the device to cuda should fix it.

Are you sure the first stage isn't still loading the model? It might appear stuck with just a green border for a while. If not, try restarting Comfy, diffusers errors often cause some loading issues for nodes.

**Comment by space-nuko** [comment]
Maybe better to split up the IF model types. At first I was confused the `T` models were supposed to go in the encoder and `I` models in the others, they seem incompatible with the wrong node types

**Comment by Zuellni** [comment]
Yes, that's a fair point. I split the loader into separate nodes now, it shouldn't be possible to connect wrong models to wrong stages anymore.

I'm still not able to reproduce the error (or rather gen stopping with no error) above sadly, but I found two errors related to switching between 4-bit and 8-bit encoder back and forth (currently requires a restart to fix), seems like another diffusers/transformers thing.

**Comment by tildebyte** [comment]
@Zuellni; While I'm here... any chance of exposing IF's [custom respacing "macros"](https://github.com/deep-floyd/IF/blob/2ad4dff7cde3cce91f237270a3cc81cae4578015/deepfloyd_if/modules/base.py#L31)

If "yes", I'll open a feature request

**Comment by Zuellni** [comment]
Can't say I've heard about that before but I assume it's not available in Diffusers and would require modifying a sampler or something similar. If so then unlikely but feel free to share if you have any more info or documentation.

**Comment by tildebyte** [comment]
@Zuellni;

>is it the same as timesteps by any chance?

Exactly! And yeah, I'm pretty sure it's only exposed when using IF "natively" (i.e. not via diffusers) - but it's entirely possible that I'm wrong 😁

**Comment by Zuellni** [comment]
I tried playing around with timesteps but the diffusers implementation is different from the deepfloyd one. They can't repeat and have to be in descending order for starters, and most of the time the resulting image is simply black. Don't think there's any point adding that seeing how it will make the nodes even more buggy.

**Comment by tildebyte** [comment]
Huzzah, it worked, even on my 8G VRAM RTX 2070. I needed to *not* use Comfy nightly, and update this repo to latest.

I've attached an updated workflow for the latest changes to the IF nodes (sorry, I don't know how to render the workspace as a PNG with the workflow embedded)

I don't know why the final image is so washed out... I did just notice

```
D:\ComfyUI\.venv\Lib\site-packages\diffusers\image_processor.py:203: FutureWarning: Passing `image` as torch tensor with value range in [-1,1] is deprecated. The expected value range for image tensor is [0,1] when passing as pytorch tensor or numpy Array. You passed `image` with value range [-0.45263671875,1.0]
```

in the console - maybe this has something to do with it?

- PNG ![ComfyUI_00003_](https://github.com/Zuellni/ComfyUI-Custom-Nodes/assets/337875/3e2f4054-5258-4f60-9f3f-3a8d37193db7)
- JSON [CustomNodes_IF_workflow.txt](https://github.com/Zuellni/ComfyUI-Custom-Nodes/files/11852437/CustomNodes_IF_workflow.txt) (change the file extension to 'json')

**Comment by Zuellni** [comment]
This saturation issue should be fixed now if you update.

**Comment by sebaxakerhtc** [comment]
> it worked

Works perfect, but how can we use local huggingface model instead of downloading it again and again?

**Comment by Zuellni** [comment]
> > it worked
> 
> Works perfect, but how can we use local huggingface model instead of downloading it again and again?

The models are downloaded once (each stage is a separate download) and cached on disk.
