### ISSUE TITLE
Error when trying to open ComfyUI with the Custom Node manager installed

### ISSUE THREAD

**Issue by MaxLak** [Zuellni/ComfyUI-Custom-Nodes#5]
C:\Users\me\Downloads\ComfyUI\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Total VRAM 6144 MB, total RAM 15790 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2060 with Max-Q Design
Using xformers cross attention
Traceback (most recent call last):
  File "C:\Users\me\Downloads\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1513, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\me\\Downloads\\ComfyUI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\.git\\__init__.py'

Cannot import C:\Users\me\Downloads\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\.git module for custom nodes: [Errno 2] No such file or directory: 'C:\\Users\\me\\Downloads\\ComfyUI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\.git\\__init__.py'

C:\Users\maxlh\Downloads\ComfyUI\ComfyUI_windows_portable>pause
Press any key to continue . . .

This doesn't happen the first time I launch, but does happen any subsequent launch.

**Comment by Zuellni** [comment]
You seem to have cloned the extension into the wrong directory as far as I can tell. There shouldn't be any git repository directly in `custom_nodes`.
