### ISSUE TITLE
ImportError: cannot import name 'BitsAndBytesConfig' from 'transformers'

### ISSUE THREAD

**Issue by mikheys** [Zuellni/ComfyUI-Custom-Nodes#9]
Hello. I keep getting this error all the time. I have already reinstalled ComfyUI and made a separate environment. What could be wrong?

Traceback (most recent call last):
  File "H:\ComfyUI\nodes.py", line 1647, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\ComfyUI\custom_nodes\ComfyUI-Custom-Nodes\__init__.py", line 67, in <module>
    module = importlib.import_module(f".Nodes.{key}", package=__name__)
  File "C:\Users\mikheys\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\ComfyUI\custom_nodes\ComfyUI-Custom-Nodes\Nodes\IF.py", line 12, in <module>
    from transformers import BitsAndBytesConfig, T5EncoderModel
ImportError: cannot import name 'BitsAndBytesConfig' from 'transformers' (H:\ComfyUI\venv\lib\site-packages\transformers\__init__.py)

Cannot import H:\ComfyUI\custom_nodes\ComfyUI-Custom-Nodes module for custom nodes: cannot import name 'BitsAndBytesConfig' from 'transformers' (H:\ComfyUI\venv\lib\site-packages\transformers\__init__.py)

**Comment by Zuellni** [comment]
Is your transformers package up to date? BitsAndBytesConfig was added in 4.27 iirc.

**Comment by mattymatty** [comment]
how do you update the transformers package?

**Comment by Zuellni** [comment]
Sorry, missed this comment.
`conda update transformers -c conda-forge` if installed with conda.
`pip install -U transformers` if installed with pip.
